name: "cangulo.nuke.prcommitsvalidations"
description: "Validate Commits in a PR"
branding:
  icon: book-open
  color: orange

# The input parameters are set as env variable and will be consumed by NUKE
inputs:
  githubToken:
    description: "Github Token"
    required: true
  validationSettingsPath:
    description: "settings to the json file with the conventional commits model"
    required: true


runs:
  using: "composite"
  steps:
    - id: commits-validation
      name: Validating pr commits
      run: ${{ github.action_path }}/app/cangulo.nuke.prcommitsvalidations --root .
      shell: bash
