name: Test GH Action

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]


jobs:
  test-gh-executable-files:
    name: Testing Executable Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validating PR commits Using executable files
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          ValidationSettingsPath: ./cicd/prCommitValidationSettings.json
          PullRequestNumber: ${{ github.event.number }}
        run: ./app/cangulo.nuke.prcommitsvalidations --root .

  test-gh-action-directly:
    name: Testing Release Candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validating PR commits Using candidate version
        uses: cangulo-actions/cangulo.nuke.prcommitsvalidations@release/0.0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          validationSettingsPath: ./cicd/prCommitValidationSettings.json