name: GH Action cangulo.nuke.prcommitsvalidations

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-conventional-commits:
    name: Validating Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validating PR commits
        # replace main by the branch you want to test
        uses: cangulo-actions/cangulo.nuke.prcommitsvalidations@main
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          ValidationSettingsPath: ./cicdSettings/prCommitValidationSettings.json
